# Generated by Django 5.2.2 on 2025-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='detected_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='battery_level',
            field=models.IntegerField(default=0),
        ),
    ]
