# Generated by Django 5.2.2 on 2025-06-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usernotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_connection_lost_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_low_battery_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
