# Generated by Django 5.2.2 on 2025-06-21 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_device_last_connection_lost_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='notify_lost_connection',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='notify_mail_out',
            field=models.BooleanField(default=True),
        ),
    ]
