# Generated by Django 5.2.2 on 2025-06-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='core_userprofile',
        ),
    ]
